version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: qdfn3af9be
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: node --version
      - run: pwd
      - run: ls
      - run: yarn test

workflows:
  app-tests:
    jobs:
      - build
