version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.16.2
        auth:
          username: qdfn3af9be
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: node --version
      - run: pwd
      - run: yarn install
  test:
    docker:
      - image: cimg/node:12.16.2
        auth:
          username: qdfn3af9be
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: ls
      - run: yarn test

workflows:
  app-tests:
    jobs:
      - build
      - test:
          requires:
            - build
