version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.16.2
        auth:
          username: qdfn3af9be
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

workflow:
  jobs:
    build_and_test:
      - build