version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.16.2
        auth:
          username: qdfn3af9be
          password: $DOCKERHUB_PASSWORD
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps-
      - run: yarn install
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: mkdir -p test-results/jest
      - run:
          name: 'Run Tests'
          command: |
            TEST=$(circleci tests glob **/__tests__/*.tsx tests/*.test.tsx | circleci tests split)
            yarn test $TEST
      - store_test_results:
          path: ./test-results/jest/

workflow:
  jobs:
    build_and_test:
      - build
