version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.16.2
        auth:
          username: qdfn3af9be
          password: $DOCKERHUB_PASSWORD
    parallelism: 1
    steps:
      - checkout
      - run: yarn install
      - run: |
          pwd
          mkdir -p test-results/jest
          ls
      - run: yarn test
      - store_test_results:
          path: test-results/jest

workflow:
  jobs:
    build_and_test:
      - build
